sudo: false
dist: trusty

# node v4+ is required for String#codePointAt support.
# node v6+ is required for destructuring assignment support.
# node v7+ is required for Object.entries.
language: node_js
node_js: '7'

addons:
  apt:
    packages:
    - racket
    # JavaScript
    - nodejs
    # Java
    - ant
    - testng

# Ubuntu 14.04 (trusty) comes with checkstyle v5 but we need v8+,
# so we fetch checkstyle from sourceforge instead of installing the package.
# TODO: Use checkstyle from apt once Travis has upgraded to Ubuntu 16+.
before_script: wget -U "" -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.10.1/checkstyle-8.10.1-all.jar
env:
- CHECKSTYLE_LIB=$PWD/checkstyle-8.10.1-all.jar

script: make test-all
